### ISSUE TITLE
ValueError during load_weights()

### ISSUE THREAD

**Issue by ottaviofogliata** [bedapudi6788/txt2txt#1]
Hi,
I found the following error while experimenting with txt2txt and the [deepcorrect](https://github.com/bedapudi6788/deepcorrect) pretrained data. Let me know if it is necessary to move the issue to the deepcorrect repository: at the moment I can't understand if the error is about the pretrained data or something related to layers in txt2txt

Thank you!
Ott.

```
 File "/data/www/project/core/src/Library/DeepCorrect/Punctuation.py", line 21, in __init__
    + '/core/dataset/deepcorrect/deeppunct_checkpoint_google_news')
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/network.py", line 1166, in load_weights
    f, self.layers, reshape=reshape)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/saving.py", line 1056, in load_weights_from_hdf5_group
    ' elements.')
ValueError: Layer #1 (named "bidirectional_1" in the current model) was found to correspond to layer embedding_1 in the save file. However the new layer bidirectional_1 expects 6 weights, but the saved weights have 1 elements.
```

**Comment by bedapudi6788** [comment]
Hi, since I modified some parts of the core model, this is expected. DeepCorrect works with version 1.0.9 of txt2txt as noted in the setup.py https://github.com/bedapudi6788/deepcorrect/blob/fb62177e3212323912f3053ae4e34ffdbc4a47c2/setup.py#L25

**Comment by ottaviofogliata** [comment]
Thanks a lot!

**Comment by bedapudi6788** [comment]
Just an FYI, I added a lot of parameters after deepcorrect to make txt2txt suitable for wide range of tasks. Right now, there is little documentation, but take a look at build_model function definition to understand what these does.
