### ISSUE TITLE
configuring input data leads to KeyError

### ISSUE THREAD

**Issue by marakhmusic** [bedapudi6788/txt2txt#3]
I changed the output examples from the ones you specified to 155. I'm getting a Keyerror. Can you help me here?
![Screenshot 2019-11-19 at 11 51 43 AM](https://user-images.githubusercontent.com/42704950/69121871-563d9b80-0ac3-11ea-88de-7e38823e06fe.png)
![Screenshot 2019-11-19 at 11 51 36 AM](https://user-images.githubusercontent.com/42704950/69121874-589ff580-0ac3-11ea-964d-8da3076cbf7a.png)

**Comment by bedapudi6788** [comment]
@mansoorkhansitar if a params file already exists in the path, the code loads the params instead of re-creating them.

Just delete your existing params file and it will work as expected.

**Comment by marakhmusic** [comment]
Yeah I just figured that out. However there's another thing I observed while testing, 
![Screenshot 2019-11-19 at 12 42 36 PM](https://user-images.githubusercontent.com/42704950/69124662-555c3800-0aca-11ea-8fa1-7432820d2439.png)
![Screenshot 2019-11-19 at 12 42 43 PM](https://user-images.githubusercontent.com/42704950/69124672-57be9200-0aca-11ea-98b2-3ac02c6faca9.png)

My question is, if the alphabet is not present in the params files, does that lead to a key error?

**Comment by bedapudi6788** [comment]
Yes. Strings needs to be one hot encoded before passing through the model. The params file has the integer encoding for each character.

**Comment by bedapudi6788** [comment]
@mansoorkhansitar http://bpraneeth.com/docs/txt2txt/ i added the documentation for each function here. You should be able to see the basic flow of what happens here.

**Comment by marakhmusic** [comment]
@bedapudi6788 Thanks a lot man! Will go through it.

**Comment by marakhmusic** [comment]
Hey @bedapudi6788 wanted to check. If i try transfer learning using the method as shown by you, can it work on sentences? as in i give it input as sentences and output as sentences.
